[vars]
DOTFILES_DIR = '{{config_root}}'

[tools]
starship = "latest"
lazygit = "latest"
github-cli = "latest"
neovim = "latest"
btop = "latest"
zoxide = "latest"
go = "latest"
rust = "latest"
uv = "latest"
ruff = "latest"
bun = "latest"
node = "lts"
pnpm = "latest"
eza = "latest"
fzf = "latest"
tmux = "latest"
"cargo:stylua" = "latest"

[tasks.install]
depends = ["link", "git", "wsl", "software", "rust"]
depends_post = "systemd"

[tasks.systemd]
depends = ["systemd"]
