[vars]
DOTFILES_DIR = "{{config_root}}/dotfiles"

[bootstrap.packages]
"pacman:starship" = "latest"
"pacman:lazygit" = "latest"
"pacman:github-cli" = "latest"
"pacman:neovim" = "latest"
"pacman:btop" = "latest"
"pacman:zoxide" = "latest"
"pacman:eza" = "latest"
"pacman:fzf" = "latest"
"pacman:tmux" = "latest"
"pacman:tombi" = "latest"

[tools]
go = "latest"
rust = "latest"
uv = "latest"
ruff = "latest"
bun = "latest"
node = "lts"
pnpm = "latest"
"cargo:stylua" = "latest"
tombi = "1.5.1"

[tasks.install]
description = "Install and configure the dotfiles environment"
depends = ["link", "git", "wsl", "software", "rust"]

[tasks.pre-commit]
description = "Format Lua files with StyLua"
run = "stylua {{ vars.DOTFILES_DIR }} && tombi format {{ vars.DOTFILES_DIR }}"

[tasks.systemd]
depends = ["systemd"]
