palette = "noctalia"
command_timeout = 500

[package]
format = "[$symbol$version]($style) "
symbol = ""
style = "bold cyan"
disabled = true 

[nodejs]
format = "[$symbol$version]($style) "
symbol = "󰎙 "

[bun]
format = "[$symbol$version]($style) "
style = "bold white"
symbol = " "

[golang]
format = "[$symbol($version )]($style)"
symbol = "󰟓 "
disabled = false
style = "bold #00ADD8"

[python]
format = "[$symbol($version )]($style)"
symbol = "󰌠 "
disabled = false
style = "bold #FFD43B"

[lua]
format = "[$symbol($version )]($style)"
symbol = " "
disabled = false

[c]
format = "[$symbol($version )]($style)"
symbol = " "
disabled = false
style = "bold #659AD2"

[cpp]
format = "[$symbol($version )]($style)"
symbol = " "
disabled = false
style = "bold #00599C"

[rust]
symbol = "󱘗 "
format = "[$symbol($version )]($style)"
style = "bold #DF5E32"
version_format = "${raw}"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "cyan"
truncation_length = 2
truncate_to_repo = false 
truncation_symbol = "~/../"
home_symbol = "~"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "\ue725 "
style = "blue"

#
# [git_status]
# format = "([$all_status$ahead_behind]($style) )"
# style = "yellow"
#
[character]
success_symbol = "[\uf105](green)"
error_symbol = "[\uf105](red)"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#458588"
red       = "#cc241d"
green     = "#98971a"
yellow    = "#d79921"
cyan      = "#689d6a"
magenta   = "#b16286"
white     = "#a89984"
black     = "#282828"

# Extended palette (Catppuccin-compatible names)
rosewater = "#fabd2f"
flamingo  = "#fb4934"
pink      = "#d3869b"
mauve     = "#b16286"
maroon    = "#fb4934"
peach     = "#fabd2f"
teal      = "#689d6a"
sky       = "#8ec07c"
sapphire  = "#83a598"
lavender  = "#d3869b"

# Text shades
text      = "#ebdbb2"
subtext1  = "#a89984"
subtext0  = "#928374"

# Surface shades
overlay2  = "#928374"
overlay1  = "#928374"
overlay0  = "#282828"
surface2  = "#282828"
surface1  = "#282828"
surface0  = "#000000"
base      = "#000000"
mantle    = "#000000"
crust     = "#000000"
# <<< NOCTALIA STARSHIP PALETTE <<<
