config_version = 13

[bar.default]
background_opacity = 0.9499999787658453
capsule_group = []
capsule_thickness = 0.99999998137354851
center = [ "clock", "cpu", "ram", "network_rx", "network_tx" ]
concave_edge_corners = false
end = [
    "bar_2",
    "topgrade-wrapper",
    "tray",
    "notifications",
    "clipboard",
    "keyboard_layout",
    "network",
    "volume",
    "brightness",
    "control-center",
    "session"
]
font_family = "JetBrains Mono Light"
font_scale = 0.9499999862164259
layer = "top"
margin_edge = 4
margin_ends = 4
padding = 10
position = "top"
radius = 4
shadow = false
show_on_workspace_switch = false
start = [ "workspaces", "spacer_2", "mpvpaper", "audio_visualizer" ]
thickness = 24

[calendar.account.personal_google]
type = "google"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000013",
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007",
    "desktop-widget-0000000000000008",
    "desktop-widget-0000000000000009",
    "desktop-widget-000000000000000a",
    "desktop-widget-000000000000000b",
    "desktop-widget-000000000000000c",
    "desktop-widget-000000000000000e",
    "desktop-widget-000000000000000f",
    "desktop-widget-0000000000000011",
    "desktop-widget-0000000000000012"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 96.0
    box_width = 240.0
    cx = 166.625
    cy = 141.4921875
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background_color = "surface"
        background_opacity = 0.80000000000000004
        clock_style = "digital"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 326.88671875
    box_width = 497.2734375
    cx = 295.26171875
    cy = 364.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "calendar"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 192.0
    box_width = 496.0
    cx = 294.625
    cy = 636.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        display = "graph"
        gauge_layout = "horizontal"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 320.0
    box_width = 256.0
    cx = 704.0
    cy = 364.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = true
        background_opacity = 0.80000000000000004
        background_padding = 32
        hide_when_no_media = false
        layout = "vertical"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 96.0
    box_width = 224.0
    cx = 426.40625
    cy = 141.4921875
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 48.0
    box_width = 240.0
    cx = 168.0
    cy = 828.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = true
        command = "ghostty"
        glyph = "terminal"
        label = "ghostty"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 48.0
    box_width = 240.0
    cx = 166.625
    cy = 764.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-0000000000000009.settings]
        background = true
        command = "zen-browser"
        glyph = "world"
        label = "Zen Browser"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-000000000000000a]
    box_height = 48.0
    box_width = 128.0
    cx = 295.26171875
    cy = 1028.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-000000000000000a.settings]
        background = true
        command = "ghostty -e fish -c \"codex\""
        glyph = "terminal"
        label = "Codex"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-000000000000000b]
    box_height = 48.0
    box_width = 128.0
    cx = 110.625
    cy = 1028.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-000000000000000b.settings]
        background = true
        command = "ghostty -e fish -c \"opencode\""
        glyph = "terminal"
        label = "opencode"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-000000000000000c]
    box_height = 48.0
    box_width = 240.0
    cx = 418.40625
    cy = 764.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-000000000000000c.settings]
        background = true
        command = "ghostty -e fish -c btop"
        glyph = "heart-rate-monitor"
        label = "Btop"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-000000000000000e]
    box_height = 48.0
    box_width = 128.0
    cx = 480.0
    cy = 1028.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-000000000000000e.settings]
        background = true
        command = "ghostty -e fish -c \"agy\""
        glyph = "terminal"
        label = "Anigravity"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-000000000000000f]
    box_height = 112.0
    box_width = 496.0
    cx = 296.0
    cy = 924.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-000000000000000f.settings]
        background = true
        command = "ghostty -e fish -c \"claude\""
        glyph = "terminal"
        label = "Claude code"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-0000000000000011]
    box_height = 80.0
    box_width = 256.0
    cx = 704.0
    cy = 160.556640625
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = -0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000011.settings]
        background = false
        bands = 24
        color_2 = "secondary"
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000012]
    box_height = 48.0
    box_width = 240.0
    cx = 418.40625
    cy = 828.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-0000000000000012.settings]
        background = true
        command = "ghostty"
        glyph = "terminal"
        label = "ghostty"
        variant = "default"

    [desktop_widgets.widget.desktop-widget-0000000000000013]
    box_height = 816.0
    box_width = 880.0
    cx = 960.0
    cy = 540.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000013.settings]
        background = false
        bloom_intensity = 0.5
        sensitivity = 2.0

[dock]
active_monitor_only = true
layer = "overlay"

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 842.0
    output = "DP-1"
    placement_height = 1024.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
layer = "top"
scale = 1.0000000074505806

[osd]
orientation = "horizontal"

[plugin_settings."nightwatch75/topgrade-wrapper"]
panel_placement = "attached"

[plugin_settings."noctalia/mpvpaper"]
run_as_systemd = true
video_directory = "/home/mark/Videos"

[plugin_settings."noctalia/notes"]
panel_placement = "attached"

[plugin_settings."weinguyen/9router-control"]
panel_open_near_click = true
panel_placement = "attached"
server_port = 1.0

[plugins]
auto_update = "all"
enabled = [
    "weinguyen/9router-control",
    "yuuto/arch-updater",
    "nightwatch75/file-search",
    "noctalia/notes",
    "raycursive/github-prs",
    "nightwatch75/topgrade-wrapper",
    "noctalia/screen_recorder",
    "noctalia/mpvpaper"
]

[shell]
app_icon_color = "primary"
app_icon_colorize = false
button_borders = true
card_borders = true
corner_radius_scale = 1.2500000186264515
font_family = "Cascadia Mono"
input_borders = true
panel_anchor_bar = "default"
popup_borders = true
settings_show_advanced = true

    [shell.animation]
    speed = 1.1500000171363354

    [shell.launcher]
    pinned = [
        "zen",
        "dev.zed.Zed",
        "google-chrome",
        "com.discordapp.Discord",
        "obsidian",
        "org.prismlauncher.PrismLauncher",
        "code",
        "com.obsproject.Studio"
    ]

    [shell.panel]
    borders = true
    clipboard_placement = "attached"
    floating_layer = "top"
    launcher_placement = "attached"
    list_item_background = false
    open_near_click_launcher = true
    polkit_placement = "attached"
    shadow = false
    transparency_mode = "glass"

    [shell.screen_corners]
    size = 32

    [shell.screenshot]
    show_cursor = true

    [shell.shadow]
    alpha = 0.93999997898936272
    direction = "down"

[theme]
builtin = "Dracula"
community_palette = "Catppuccin Frappe Peach"
pure_black_dark = true
source = "community"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "kitty", "qt", "starship" ]
    community_ids = [
        "antigravity",
        "claude-code",
        "codex",
        "opencode",
        "pi-agent",
        "zen-browser",
        "discord",
        "micro",
        "neovim",
        "obsidian",
        "vscode",
        "zed",
        "prismlauncher",
        "steam",
        "fastfetch",
        "obs",
        "bat",
        "fzf",
        "lazygit",
        "rio",
        "tmux"
    ]

[wallpaper]
directory = "/home/mark/walls"
enabled = true
fill_mode = "stretch"

    [wallpaper.default]
    path = "/home/mark/walls/poly/a_video_game_screen_with_a_diamond_and_green_lights.png"

    [wallpaper.last]
    path = "/home/mark/walls/poly/a_video_game_screen_with_a_diamond_and_green_lights.png"

    [wallpaper.monitors.DP-1]
    path = "/home/mark/walls/poly/a_video_game_screen_with_a_diamond_and_green_lights.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/mark/walls/poly/a_video_game_screen_with_a_diamond_and_green_lights.png"

[widget.active_window]
enabled = false
icon_size = 20

[widget.bar_2]
type = "salemsayed/codexbar-meter:bar"

[widget.clipboard]
enabled = true

[widget.launcher]
enabled = false
glyph = "apps-filled"

[widget.media]
enabled = false
interactive = false
max_length = 200
title_scroll = "always"

[widget.mpvpaper]
enabled = false
type = "noctalia/mpvpaper:mpvpaper"

[widget.session]
enabled = true

[widget.spacer_2]
enabled = false
type = "spacer"

[widget.topgrade-wrapper]
type = "nightwatch75/topgrade-wrapper:topgrade-wrapper"

[widget.tray]
drawer = true

[widget.wallpaper]
enabled = false

[widget.workspaces]
capsule_padding = 10
enabled = true
focused_output_only = true
font_scale = 1.2
max_label_chars = 2
pill_scale = 0.85000000000000009
style = "minimal"