gui:
  theme:
    activeBorderColor:
      - '#ed8649'
      - bold
    inactiveBorderColor:
      - '#8a7f6f'
    optionsTextColor:
      - '#ed8649'
    selectedLineBgColor:
      - '#26211c'
    cherryPickedCommitBgColor:
      - '#26211c'
    cherryPickedCommitFgColor:
      - '#66ed49'
    unstagedChangesColor:
      - '#ff807a'
    defaultFgColor:
      - '#f5e8c7'
    searchingActiveBorderColor:
      - '#ed8649'
  showIcons: true
  nerdFontsVersion: "3"
