gui:
  theme:
    activeBorderColor:
      - "#d79921"
      - bold
    inactiveBorderColor:
      - "#b8bb26"
    searchingActiveBorderColor:
      - "#fe8019"
      - bold
    optionsTextColor:
      - "#a89984"
    selectedLineBgColor:
      - "#a89984"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#a89984"
    cherryPickedCommitBgColor:
      - "#fe8019"
    markedBaseCommitFgColor:
      - "#fe8019"
    markedBaseCommitBgColor:
      - "#fb4934"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
  showIcons: true
  nerdFontsVersion: "3"
