gui:
  theme:
    activeBorderColor:
      - '#e78a4e'
      - bold
    inactiveBorderColor:
      - '#827770'
    optionsTextColor:
      - '#e78a4e'
    selectedLineBgColor:
      - '#474240'
    cherryPickedCommitBgColor:
      - '#3c3836'
    cherryPickedCommitFgColor:
      - '#a9b665'
    unstagedChangesColor:
      - '#ea6962'
    defaultFgColor:
      - '#ddc7a1'
    searchingActiveBorderColor:
      - '#e78a4e'
  showIcons: true
  nerdFontsVersion: "3"
