-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

hl.monitor({

    output = "DP-1",
    mode = "preferred",
    position = "0x375",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "preferred",
    position = "1280x0",
    scale = "1",
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal = "kitty"
local fileManager = "nautilus"
local menu = "hyprlauncher"
local browser = "google-chrome-stable"
local noctalia = "noctalia"
local noctalia_ipc = noctalia .. " msg "

---------------------
--- GLOBAL STATES ---
---------------------

local MAX_ZOOM = 3.0
local MIN_ZOOM = 1.0
local is_zoomed = false

---------------------
---- HELPER FUNCTIONS ----
---------------------

local function set_zoom(offset)
    local current = hl.get_config("cursor.zoom_factor") or 1.0
    local new_zoom = 1.0

    if offset then
        new_zoom = math.min(MIN_ZOOM + MAX_ZOOM - 1.0, math.max(MIN_ZOOM, current + offset))
    end

    is_zoomed = new_zoom > 1.0

    hl.config({
        cursor = {
            zoom_factor = new_zoom,
        },
    })
end

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function()
    hl.exec_cmd(noctalia)
    hl.exec_cmd(terminal)
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
-- 	ecosystem = {
-- 		enforce_permissions = true,
-- 	},
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- See https://wiki.hypr.land/Configuring/Basics/Variables/

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 4,
        border_size = 1,
    },

    decoration = {
        rounding = 8,
        rounding_power = 2,

        active_opacity = 0.94,
        inactive_opacity = 0.90,
        fullscreen_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 8,
            render_power = 3,
        },

        blur = {
            enabled = true,
            size = 5,
            passes = 3,
            vibrancy = 0.1696,
        },
    },
})

-----------------------
---- NOCTALIA RULES ----
-----------------------

hl.layer_rule({
    name = "noctalia",
    match = {
        namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$",
    },
    no_anim = true,
    ignore_alpha = 0.5,
    blur = true,
    blur_popups = true,
})

-- Noctalia Settings

hl.window_rule({
    match = {
        class = "dev.noctalia.Noctalia",
    },
    float = true,
    size = { 1080, 920 },
})

-----------------------
---- FILE MANAGERS ----
-----------------------

hl.window_rule({
    name = "nautilus",
    match = {
        class = "org.gnome.Nautilus",
    },
    float = true,
    size = { 1080, 820 },
})

hl.window_rule({
    name = "dolphin",
    match = {
        class = "org.kde.dolphin",
    },
    float = true,
    size = { 1080, 820 },
})

--------------------------------------------------------------------------------
-- ANIMATION CONFIGURATION
--------------------------------------------------------------------------------

local speed_fast = 3.0
local speed_normal = 4.5
local speed_slow = 5.0
local speed_out = 4.5

--------------------------------------------------------------------------------
-- CURVES
--------------------------------------------------------------------------------

-- Smooth and clean
hl.curve("smooth", {
    type = "bezier",
    points = {
        { 0.22, 1.0 },
        { 0.36, 1.0 },
    },
})

-- Fast acceleration with soft landing
hl.curve("smoothOut", {
    type = "bezier",
    points = {
        { 0.16, 1.0 },
        { 0.30, 1.0 },
    },
})

-- Soft fade
hl.curve("soft", {
    type = "bezier",
    points = {
        { 0.25, 0.1 },
        { 0.25, 1.0 },
    },
})

-- Very fast
hl.curve("quick", {
    type = "bezier",
    points = {
        { 0.15, 0.0 },
        { 0.10, 1.0 },
    },
})

--------------------------------------------------------------------------------
-- SPRING CURVES
--------------------------------------------------------------------------------

-- Main spring
hl.curve("smoothSpring", {
    type = "spring",
    mass = 1.0,
    stiffness = 380,
    dampening = 30,
})

-- Slightly playful spring
hl.curve("playfulSpring", {
    type = "spring",
    mass = 1.0,
    stiffness = 430,
    dampening = 28,
})

hl.curve("special_smooth", {
    type = "bezier",
    points = {
        { 0.22, 1.0 },
        { 0.36, 1.0 },
    },
})

--------------------------------------------------------------------------------
-- GLOBAL
--------------------------------------------------------------------------------

hl.animation({
    leaf = "global",
    enabled = true,
    speed = speed_normal,
    bezier = "smooth",
})

--------------------------------------------------------------------------------
-- WINDOWS
--------------------------------------------------------------------------------

-- Normal window movement
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = speed_normal,
    spring = "smoothSpring",
})

-- Window opening
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = speed_fast,
    spring = "playfulSpring",
    style = "popin 85%",
})

-- Window closing
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = speed_out,
    bezier = "quick",
    style = "popin 85%",
})

hl.animation({
    leaf = "specialWorkspaceIn",
    enabled = true,
    speed = 4,
    bezier = "special_smooth",
    style = "slidevert",
})

hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 5,
    bezier = "special_smooth",
    style = "slidevert",
})

--------------------------------------------------------------------------------
-- FADE
--------------------------------------------------------------------------------

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = speed_fast,
    bezier = "soft",
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = speed_fast,
    bezier = "soft",
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = speed_out,
    bezier = "quick",
})

--------------------------------------------------------------------------------
-- LAYERS
--------------------------------------------------------------------------------

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = speed_normal,
    bezier = "smooth",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = speed_fast,
    bezier = "smoothOut",
    style = "fade",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = speed_out,
    bezier = "quick",
    style = "fade",
})

hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = speed_fast,
    bezier = "soft",
})

hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = speed_out,
    bezier = "quick",
})

--------------------------------------------------------------------------------
-- WORKSPACES
--------------------------------------------------------------------------------

-- Main workspace switching
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = speed_normal,
    bezier = "smooth",
    style = "slidefade 18%",
})

-- Workspace entering
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = speed_normal,
    bezier = "smooth",
    style = "slidefade 18%",
})

-- Workspace leaving
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = speed_fast,
    bezier = "quick",
    style = "slidefade 18%",
})

--------------------------------------------------------------------------------
-- CURSOR ZOOM
--------------------------------------------------------------------------------

hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = speed_fast,
    bezier = "quick",
})

--------------------------------------------------------------------------------
-- WORKSPACE RULES
--------------------------------------------------------------------------------

-- Smart gaps example
-- hl.workspace_rule({
-- 	workspace = "w[tv1]",
-- 	gaps_out = 0,
-- 	gaps_in = 0,
-- })

-- hl.workspace_rule({
-- 	workspace = "f[1]",
-- 	gaps_out = 0,
-- 	gaps_in = 0,
-- })

-- hl.window_rule({
-- 	name = "no-gaps-wtv1",
-- 	match = {
-- 		float = false,
-- 		workspace = "w[tv1]",
-- 	},
-- 	border_size = 0,
-- 	rounding = 0,
-- })

-----------------------
---- DWINDLE LAYOUT ----
-----------------------

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-----------------------
---- MASTER LAYOUT ----
-----------------------

hl.config({
    master = {
        new_status = "master",
    },
})

-----------------------
---- SCROLLING LAYOUT ----
-----------------------

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout = "us,th",
        kb_variant = "",
        kb_model = "",
        kb_options = "grp:win_space_toggle",
        kb_rules = "",

        follow_mouse = 1,

        sensitivity = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

----------------
---- GESTURES ----
----------------

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-----------------------
---- DEVICE CONFIG ----
-----------------------

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

-----------------------
---- APPLICATIONS ----
-----------------------

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))

hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-----------------------
---- WINDOW CONTROL ----
-----------------------

hl.bind(mainMod .. " + Q", hl.dsp.window.close())

hl.bind(
    mainMod .. " + V",
    hl.dsp.window.float({
        action = "toggle",
    })
)

hl.bind(
    mainMod .. " + F",
    hl.dsp.window.fullscreen({
        action = "toggle",
    })
)

hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

-----------------------
---- NOCTALIA ----
-----------------------

hl.bind(mainMod .. " + COMMA", hl.dsp.exec_cmd(noctalia_ipc .. "settings-toggle"))

hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(noctalia_ipc .. "panel-toggle launcher"))

hl.bind("ALT + Tab", hl.dsp.exec_cmd(noctalia_ipc .. "window-switcher"))

hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(noctalia_ipc .. "panel-toggle wallpaper"))

hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.exec_cmd(noctalia_ipc .. "panel-toggle noctalia/notes:panel "))

hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(noctalia_ipc .. "desktop-widgets-toggle-edit"))

-----------------------
---- FOCUS ----
-----------------------

hl.bind(
    mainMod .. " + CTRL + H",
    hl.dsp.focus({
        direction = "left",
    })
)

hl.bind(
    mainMod .. " + CTRL + L",
    hl.dsp.focus({
        direction = "right",
    })
)

hl.bind(
    mainMod .. " + CTRL + K",
    hl.dsp.focus({
        direction = "up",
    })
)

hl.bind(
    mainMod .. " + CTRL + J",
    hl.dsp.focus({
        direction = "down",
    })
)

-----------------------
---- MOVE WINDOWS ----
-----------------------

hl.bind(
    mainMod .. " + SHIFT + H",
    hl.dsp.window.move({
        direction = "left",
    })
)

hl.bind(
    mainMod .. " + SHIFT + J",
    hl.dsp.window.move({
        direction = "down",
    })
)

hl.bind(
    mainMod .. " + SHIFT + K",
    hl.dsp.window.move({
        direction = "up",
    })
)

hl.bind(
    mainMod .. " + SHIFT + L",
    hl.dsp.window.move({
        direction = "right",
    })
)

-----------------------
---- ZOOM ----
-----------------------

hl.bind(mainMod .. " + Equal", function()
    set_zoom(0.3)
end)

hl.bind(mainMod .. " + Minus", function()
    set_zoom(-0.3)
end)

hl.bind(mainMod .. " + BACKSPACE", function()
    set_zoom()
end)

-----------------------
---- SCREENSHOT ----
-----------------------

hl.bind("PRINT", hl.dsp.exec_cmd(noctalia_ipc .. "screenshot-region"))

-----------------------
---- WORKSPACES ----
-----------------------

for i = 1, 10 do
    local key = i % 10

    hl.bind(
        mainMod .. " + " .. key,
        hl.dsp.focus({
            workspace = i,
        })
    )

    hl.bind(
        mainMod .. " + SHIFT + " .. key,
        hl.dsp.window.move({
            workspace = i,
        })
    )
end

-----------------------
---- SPECIAL WORKSPACE ----
-----------------------

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(
    mainMod .. " + SHIFT + S",
    hl.dsp.window.move({
        workspace = "special:magic",
    })
)

-----------------------
---- WORKSPACE SCROLL ----
-----------------------

hl.bind(
    mainMod .. " + mouse_down",
    hl.dsp.focus({
        workspace = "e+1",
    })
)

hl.bind(
    mainMod .. " + mouse_up",
    hl.dsp.focus({
        workspace = "e-1",
    })
)

-----------------------
---- MOUSE WINDOW CONTROL ----
-----------------------

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), {
    mouse = true,
})

hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), {
    mouse = true,
})

-----------------------
---- AUDIO ----
-----------------------

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), {
    locked = true,
    repeating = true,
})

-----------------------
---- BRIGHTNESS ----
-----------------------

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), {
    locked = true,
    repeating = true,
})

-----------------------
---- MEDIA ----
-----------------------

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), {
    locked = true,
})

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), {
    locked = true,
})

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), {
    locked = true,
})

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), {
    locked = true,
})

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See:
-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-----------------------
---- MAXIMIZE RULE ----
-----------------------

local suppressMaximizeRule = hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },

    suppress_event = "maximize",
})

-- suppressMaximizeRule:set_enabled(false)

-----------------------
---- XWAYLAND DRAGS ----
-----------------------

hl.window_rule({
    name = "fix-xwayland-drags",

    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },

    no_focus = true,
})

-----------------------
---- HYPRLAND RUN ----
-----------------------

hl.window_rule({
    name = "move-hyprland-run",

    match = {
        class = "hyprland-run",
    },

    move = "20 monitor_h-120",
    float = true,
})

-----------------------
---- NOCTALIA THEME ----
-----------------------

require("noctalia").apply_theme()
