source (dirname (status filename))/functions/alias.fish
source (dirname (status filename))/functions/zoxide.fish

set -U fish_greeting ""

# fzf theme (generated by Noctalia user-template)
set -gx FZF_DEFAULT_OPTS_FILE "$HOME/.config/fzf/fzfrc"

# bun
set --export BUN_INSTALL "$HOME/.bun"
set --export PATH $BUN_INSTALL/bin $PATH

# starship
starship init fish | source

set -U fish_user_paths ~/.cargo/bin $fish_user_paths

fastfetch

set -g fish_ambiguous_width 1
set -g fish_emoji_width 2


# Added by Antigravity CLI installer
set -gx PATH "/home/mark/.local/bin" $PATH
fish_add_path $HOME/trek/bin

# opencode
fish_add_path /home/mark/.opencode/bin

# pnpm
set -gx PNPM_HOME "/home/mark/.local/share/pnpm"
if not string match -q -- "$PNPM_HOME/bin" $PATH
  set -gx PATH "$PNPM_HOME/bin" $PATH
end
# pnpm end

# Wasmer
export WASMER_DIR="/home/mark/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"

set -gx WASMTIME_HOME "$HOME/.wasmtime"

string match -r ".wasmtime" "$PATH" > /dev/null; or set -gx PATH "$WASMTIME_HOME/bin" $PATH

# proto
set -gx PROTO_HOME "$HOME/.proto";
set -gx PATH "$PROTO_HOME/shims" "$PROTO_HOME/bin" $PATH;